[default]
all-features = true
output-dir = "target/tarpaulin"
out = ["Html", "Xml", "Lcov"]
fail-under = 75
timeout = 300
no-fail-fast = true
ignore-tests = false
exclude-files = ["*/tests/*", "*/examples/*", "*/benches/*", "*/macros/*"]
generate-link = true
